# Generated by Django 3.2.8 on 2021-11-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
